# Generated by Django 4.1.7 on 2023-03-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_pessoa_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(db_column='nome', default=1, max_length=50),
            preserve_default=False,
        ),
    ]
