# Generated by Django 4.1.7 on 2023-04-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pessoa_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='nome',
            new_name='tarefa',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='importancia',
            field=models.BooleanField(default=False),
        ),
    ]
