# Generated by Django 4.1.7 on 2023-04-07 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_nome_pessoa_tarefa_pessoa_importancia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='tarefa',
            new_name='nome',
        ),
    ]
