# Generated by Django 4.1.7 on 2023-04-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_tarefa_pessoa_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='importancia',
            field=models.CharField(db_column='importancia', max_length=10),
        ),
    ]
